<?php

require_once __DIR__ . "/../vendor/autoload.php";

use IDRsolutions\BuildVuPhpClient\Converter;

$endpoint = "http://localhost:8080/microservice-example/";

/* Set up the conversion options */

// Options to convert from a file upload:
// Add to 'parameters' with API values that are sent to the server. See
// https://github.com/idrsolutions/buildvu-microservice-example/blob/master/API.md
// for more details.
$options = array(
    'endpoint' => $endpoint, // Required
    'file' => __DIR__ . 'path/to/file.pdf', // Required
    'parameters' => array(
        'input' => Converter::INPUT_UPLOAD, // Required
        'callbackUrl' => 'http://url.to.callback.to/' // Optional
    )
);
    
// Options to convert from a url download:
// Alternatively you can get the server to download the pdf file directly
// With the below configuration
/*$options = array(
    'endpoint' => $endpoint,
    'parameters' => array(
        'input' => Converter::INPUT_DOWNLOAD,
        'url' => 'http://path.to/file.pdf'
    )
);*/


try {
    /* Start the conversion */
    $conversion_results = Converter::convert($options);
    
    // The results are the response generated by the server
     // downloadUrl provides a link to download the converted file
    echo $conversion_results['downloadUrl'];
    
    // With the reults you can then use the downloadOutput method to
    // Download the converted output to the specified directory
    Converter::downloadOutput($conversion_results, __DIR__ . '/');

} catch (Exception $e) {
    echo $e->getMessage();
    echo $e->getTrace();
    exit(1);
}
